Add option to Change the created_via field.
wp-graphql/wp-graphql-woocommerce pull request #609
Opened 2022-02-19 12:35 UTC by scottyzen

Can be useful when WooCommerce is being used from multiply sources. For example, with plugins like Point of Sale for WooCommerce.

### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository.

- [ ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [ ] Make sure you are requesting to pull request from a **topic/feature/bugfix/devops branch** (right side). Don't pull request from your master!
- [ ] Have you ensured/updated that CLI tests to extend coverage to any new logic. Learn how to modify the tests [here](https://woographql.com/contributing/2-local-testing).

What does this implement/fix? Explain your changes.
---------------------------------------------------
…

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------

- **WooGraphQL Version:** 0.10.7
- **WPGraphQL Version:** 1.6.12
- **WordPress Version:** 5.9
- **WooCommerce Version:** 6.2.0

2022-02-26 01:20 UTC, kidunot89 requested changes
I'm fine with this change, but add it to the unit tests [here](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/tests/wpunit/CheckoutMutationTest.php) and [here](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/tests/wpunit/OrderMutationsTest.php)

2023-03-13 17:24 UTC, sbolinger-godaddy commented
Can this also be added to the checkout mutation? Since the checkout creates an order, the checkout input should accept `createdVia`.

2023-05-22 19:52 UTC, kidunot89 commented
@scottyzen Get this rebased and we can merge it if it passes CI.

2023-08-02 21:04 UTC, kidunot89 commented on tests/wpunit/CheckoutMutationTest.php
> +		}
@scottyzen What's the purpose of this change? Also you didn't change the `checkout` mutation but the `createOrder` mutation. You should update the `OrderMutationsTest` instead.

2023-08-02 21:05 UTC, kidunot89 commented on tests/wpunit/OrderMutationsTest.php
> +			'billing'            => array(
Please revert WooGraphQL uses short array syntax `[ ]`

2023-08-02 21:05 UTC, kidunot89 commented on tests/wpunit/OrderMutationsTest.php
> +			'billing'            => array(
Please revert WooGraphQL uses short array syntax `[ ]`

2023-08-02 21:05 UTC, kidunot89 commented on tests/wpunit/OrderMutationsTest.php
> +			'billing'            => array(
Please revert WooGraphQL uses short array syntax `[ ]`

2023-08-02 21:07 UTC, kidunot89 requested changes
@scottyzen Your current changes only effect the `createOrder` mutation, you might want to use this functionality in the `checkout` mutation as well. Also, these changes need to be tested in the `CheckoutMutationTest` and `OrderMutationsTest`

2026-06-12 17:16 UTC, closed without merging