Fix Product Variation Shipping Class
wp-graphql/wp-graphql-woocommerce pull request #895
Opened 2024-10-04 08:02 UTC by robbiebel

### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository.

- [x ] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x ] Make sure you are requesting to pull request from a **topic/feature/bugfix/devops branch** (right side). Don't pull request from your master!
- [x ] Have you ensured/updated that CLI tests to extend coverage to any new logic. Learn how to modify the tests [here](https://woographql.com/contributing/2-local-testing).

What does this implement/fix? Explain your changes.
---------------------------------------------------
…
Product Variations Shipping Classes was not implemented correctly.

Does this close any currently open issues?
------------------------------------------
…
No

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…
It's a small fix to understand easily to look changes.

2024-10-11 14:49 UTC, kidunot89 requested changes
@robbiebel Sorry for the slow review of this. It's failing CI and I can't merge it as long as it is.

2024-10-18 14:31 UTC, robbiebel commented
Hi @kidunot89, I'm also sorry for slowness on my side. 

I have tried before create first PR and now again. But I have not succeed testing on my local although I tried a few things. 

> testable_app  | Warning: The 'woocommerce' plugin could not be found.
testable_app  | Warning: The 'woocommerce-gateway-stripe' plugin could not be found.
testable_app  | Warning: The 'wp-graphql' plugin could not be found.
testable_app  | Warning: The 'wp-graphql-jwt-authentication' plugin could not be found.
testable_app  | Plugin 'wp-graphql-woocommerce' activated.
testable_app  | Error: Only activated 1 of 5 plugins.
testable_app exited with code 1

2024-11-07 00:24 UTC, kidunot89 requested changes
I think I understand what you're trying to achieve here but there is some work to be done. See my comments and also take a look at [CONTRIBUTING.md](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/.github/CONTRIBUTING.md#setting-up-an-environment-to-run-the-wpunit-tests)

2024-11-09 14:58 UTC, robbiebel commented on includes/type/interface/class-product-variation.php
> +				'type'        => 'ShippingClass',
I thought this is the type: 
https://woographql.com/schema/definition/-shipping-class

2024-11-09 15:01 UTC, robbiebel commented
> I think I understand what you're trying to achieve here but there is some work to be done. See my comments and also take a look at [CONTRIBUTING.md](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/.github/CONTRIBUTING.md#setting-up-an-environment-to-run-the-wpunit-tests)

I already followed CONTRIBUTING.md but not succeeded even I have good experience in Docker. The CONTRIBUTING.md has many missing parts for fresh install.

But I achieved to run docker applications by tracing the code and filling the missing parts. I recommend that updating the CONTRIBUTING.md

2024-11-12 15:49 UTC, kidunot89 commented on includes/type/interface/class-product-variation.php
> +				'type'        => 'ShippingClass',
That means this needs to be provided with a resolver that resolves to the `TermNode`. The resolver should looks something like this.
```php
'resolve'     => static function ( $source, array $args, $context  ) {
        $id = $source->shipping_class_id;
        if ( $id ) {
	        return $context->get_loader( "term" )->load_deferred( $id );
        }

        return null;
},

2025-01-26 22:18 UTC, closed without merging